In [1]:
# Creating an array 'rank'
import pandas as pd
import numpy as np
rank = np.array(['rank1', 'rank2', 'rank3', 'rank4', 'rank5'])
print(" The array 'rank' consists of elements : ", rank)

 The array 'rank' consists of elements :  ['rank1' 'rank2' 'rank3' 'rank4' 'rank5']


In [2]:
# Creating a dictionary 'exam_data_array'
exam_data_array = {
    "Name" : ["Herin", "Darshan", "Jainik", "KD","James"],
    "Score" : [ 20, 17, 18, 23, 19 ],
    "Attempts" : [ 2, 1, 3, 2, 4 ],
    "Qualify" : [ "yes", "yes", "no", "yes", "no" ]
}
print("A dictionary 'exam_data_array' is given as follows :- ",exam_data_array)

A dictionary 'exam_data_array' is given as follows :-  {'Name': ['Herin', 'Darshan', 'Jainik', 'KD', 'James'], 'Score': [20, 17, 18, 23, 19], 'Attempts': [2, 1, 3, 2, 4], 'Qualify': ['yes', 'yes', 'no', 'yes', 'no']}


In [5]:
# Creating a dataframe 'exam',having data from exam_data_array
# and array rank as its label
exam = pd.DataFrame( exam_data_array, index = rank)
print("A dataframe 'exam' is given as :- ",exam)

A dataframe 'exam' is given as :-            Name  Score  Attempts Qualify
rank1    Herin     20         2     yes
rank2  Darshan     17         1     yes
rank3   Jainik     18         3      no
rank4       KD     23         2     yes
rank5    James     19         4      no


In [6]:
# Summary of basic information and its data
print(exam.index)
print("\n", exam.columns)
print("\n", exam.dtypes)

Index(['rank1', 'rank2', 'rank3', 'rank4', 'rank5'], dtype='object')

 Index(['Name', 'Score', 'Attempts', 'Qualify'], dtype='object')

 Name        object
Score        int64
Attempts     int64
Qualify     object
dtype: object


In [7]:
print(exam["Name"])

rank1      Herin
rank2    Darshan
rank3     Jainik
rank4         KD
rank5      James
Name: Name, dtype: object


In [8]:
print(exam[["Name", "Score"]])

          Name  Score
rank1    Herin     20
rank2  Darshan     17
rank3   Jainik     18
rank4       KD     23
rank5    James     19


In [9]:
print(exam.describe)

<bound method NDFrame.describe of           Name  Score  Attempts Qualify
rank1    Herin     20         2     yes
rank2  Darshan     17         1     yes
rank3   Jainik     18         3      no
rank4       KD     23         2     yes
rank5    James     19         4      no>


In [10]:
print(exam.head(3))

          Name  Score  Attempts Qualify
rank1    Herin     20         2     yes
rank2  Darshan     17         1     yes
rank3   Jainik     18         3      no


In [11]:
print(exam.tail(3))

         Name  Score  Attempts Qualify
rank3  Jainik     18         3      no
rank4      KD     23         2     yes
rank5   James     19         4      no


In [12]:
print(exam.loc[(exam["Score"] >= 15) & (exam["Score"] <= 20 )])
# Other method is : print( exam["Score"].between( 15,20 ) )

          Name  Score  Attempts Qualify
rank1    Herin     20         2     yes
rank2  Darshan     17         1     yes
rank3   Jainik     18         3      no
rank5    James     19         4      no


In [13]:
print( exam.sort_values( ["Score"] ) )
print( exam.sort_values( ["Name"], ascending = False ) )
# print( exam.sort_values( by=["Score","Name"], ascending = [True, False] ))

          Name  Score  Attempts Qualify
rank2  Darshan     17         1     yes
rank3   Jainik     18         3      no
rank5    James     19         4      no
rank1    Herin     20         2     yes
rank4       KD     23         2     yes
          Name  Score  Attempts Qualify
rank4       KD     23         2     yes
rank5    James     19         4      no
rank3   Jainik     18         3      no
rank1    Herin     20         2     yes
rank2  Darshan     17         1     yes


In [14]:
exam.replace( {"Qualify" : "yes"}, "True", inplace = True )
exam.replace( {"Qualify" : "no" }, "False", inplace = True )
exam
# print( exam["Qaulify"].rename( {"yes" : "True", "no" : "False"}, axis = "rows")) # df = pd.DataFrame()
# df = exam['Qualify'].map( {'yes' : 'True', 'no' : 'False'} )
# print( df )

Name  Score  Attempts Qualify
rank1    Herin     20         2    True
rank2  Darshan     17         1    True
rank3   Jainik     18         3   False
rank4       KD     23         2    True
rank5    James     19         4   False

In [15]:
print(	exam.iloc[ 0::2, [1,3] ] )

       Score Qualify
rank1     20    True
rank3     18   False
rank5     19   False


In [16]:
print(exam.loc[(exam["Attempts"]< 2) & (exam["Score"] > 15 )])

          Name  Score  Attempts Qualify
rank2  Darshan     17         1    True


In [17]:
exam["Name"].replace( "James", "Suresh", inplace = True )
print(exam)
# exam["Name"] = exam["Name"].replace('James','Suresh')

          Name  Score  Attempts Qualify
rank1    Herin     20         2    True
rank2  Darshan     17         1    True
rank3   Jainik     18         3   False
rank4       KD     23         2    True
rank5   Suresh     19         4   False


C:\Users\Administrator\AppData\Local\Temp\ipykernel_77820\382977634.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  exam["Name"].replace( "James", "Suresh", inplace = True )


In [18]:
print(exam["Attempts"].sum())

12


In [19]:
df1 = pd.DataFrame({
    "Name": ["Neep"], 
    "Score": [21],
    "Attempts": [3],
    "Qualify": ["False"]
}, index=["rank6"])
exam = pd.concat([exam, df1])
exam

Name  Score  Attempts Qualify
rank1    Herin     20         2    True
rank2  Darshan     17         1    True
rank3   Jainik     18         3   False
rank4       KD     23         2    True
rank5   Suresh     19         4   False
rank6     Neep     21         3   False

In [20]:
exam['exam_name'] = ['Jee', 'Neet', 'Jee', 'Jee Advanced', 'Bitsat', 'Viteee' ]
exam

Name  Score  Attempts Qualify     exam_name
rank1    Herin     20         2    True           Jee
rank2  Darshan     17         1    True          Neet
rank3   Jainik     18         3   False           Jee
rank4       KD     23         2    True  Jee Advanced
rank5   Suresh     19         4   False        Bitsat
rank6     Neep     21         3   False        Viteee

In [21]:
exam.drop('exam_name', inplace = True, axis = 1 )
exam
# Other method is : del exam["exam_name"]

Name  Score  Attempts Qualify
rank1    Herin     20         2    True
rank2  Darshan     17         1    True
rank3   Jainik     18         3   False
rank4       KD     23         2    True
rank5   Suresh     19         4   False
rank6     Neep     21         3   False

In [24]:
arr = pd.Series(rank)
print(arr)

0    rank1
1    rank2
2    rank3
3    rank4
4    rank5
dtype: object


In [25]:
s1 = pd.Series ( exam_data_array )
print( s1 )

Name        [Herin, Darshan, Jainik, KD, James]
Score                      [20, 17, 18, 23, 19]
Attempts                        [2, 1, 3, 2, 4]
Qualify                 [yes, yes, no, yes, no]
dtype: object


In [26]:
s2 = pd.Series( exam["Name"] )
print(s2)

rank1      Herin
rank2    Darshan
rank3     Jainik
rank4         KD
rank5     Suresh
rank6       Neep
Name: Name, dtype: object


In [ ]:
import numpy as np
import math as mt
import satistics as st

In [27]:
arr = np.arange( 30, 71, 2 )
print( arr )

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [28]:
arr_zeros = np.zeros( (10), dtype = int)
print( arr_zeros )
arr_ones = np.ones( (10), dtype = int)
print( arr_ones )
arr_fives = np.full( (10), 5 )
print( arr_fives )
# arr_zeros = np.zeros(10) # arr_ones = np.ones(10)
# arr_fives = np.ones(10)*5

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


In [29]:
vector = np.linspace( 5, 50, 10 )
print(vector)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [30]:
matrix = np.arange( 10, 22 ).reshape( (3,4) )
print(matrix)
print( np.sum(matrix) )
print( matrix.sum( axis = 0 ) )
print( matrix.sum( axis = 1 ) )

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
186
[42 45 48 51]
[46 62 78]


In [31]:
a = np.array( [[1,2,3, np.nan], [np.nan, 6, np.nan, 8], [9, np.nan, 11, 12] ] )
print(a)
print("\n",np.isnan(a))
# Other method is : pd.isnull(a)

[[ 1.  2.  3. nan]
 [nan  6. nan  8.]
 [ 9. nan 11. 12.]]

 [[False False False  True]
 [ True False  True False]
 [False  True False False]]


In [32]:
# Creating an array with elements
x = np.array( [4.2, 5.6, 8.9, 9.1, -3.6, -4.5, -5.7] )
print(x)
r = [ round(ele) for ele in x ]
print("Rounded-off array x : ", np.round(x) )
print("Floor	: ", np.floor(x) )
print("Ceil	: ", np.ceil(x) )
print("Truncated array x	: ", np.trunc(x) )
print("Round	: ", r )

[ 4.2  5.6  8.9  9.1 -3.6 -4.5 -5.7]
Rounded-off array x :  [ 4.  6.  9.  9. -4. -4. -6.]
Floor	:  [ 4.  5.  8.  9. -4. -5. -6.]
Ceil	:  [ 5.  6.  9. 10. -3. -4. -5.]
Truncated array x	:  [ 4.  5.  8.  9. -3. -4. -5.]
Round	:  [4, 6, 9, 9, -4, -4, -6]


In [34]:
arr = np.array([ [89,75,45,65], [65,14,78,49], [32,46,55,73] ])
print(arr)
arr = arr.flatten()
print(arr)
print("Maximum : ", arr.max() )
print("Minimum : ", arr.min() )
print("Median : ", np.median(arr) )
print("Mean : ", np.mean(arr) )
print("Standard Deviation : ", np.std(arr) )
print("Covariance : ", np.cov(arr) )
print("Weighted Average : ", np.average(arr) )

[[89 75 45 65]
 [65 14 78 49]
 [32 46 55 73]]
[89 75 45 65 65 14 78 49 32 46 55 73]
Maximum :  89
Minimum :  14
Median :  60.0
Mean :  57.166666666666664
Standard Deviation :  20.370866997313154
Covariance :  452.69696969696963
Weighted Average :  57.166666666666664


In [35]:
arr = arr.reshape((3,4))
print(arr)
print(arr.min(axis = 1 ))
print(arr.max(axis = 1 ))

[[89 75 45 65]
 [65 14 78 49]
 [32 46 55 73]]
[45 14 32]
[89 78 73]


In [36]:
data_type = [('name','S15'), ('class', int), ('height', float) ]
students_details = [('Herin', 4, 45.6),
('Rohan', 6, 52.3),
('Rahul', 4, 53.6)]
students = np.array( students_details, dtype = data_type ) 
print( students )
print( np.sort( students, order = ['class','height'] ))

[(b'Herin', 4, 45.6) (b'Rohan', 6, 52.3) (b'Rahul', 4, 53.6)]
[(b'Herin', 4, 45.6) (b'Rahul', 4, 53.6) (b'Rohan', 6, 52.3)]
